using Autofac;
using Autofac.Builder;
using Autofac.Integration.Mvc;
using Autofac.Integration.Wcf;
using JieNor.Megi.Common.ServiceManager;
using JieNor.Megi.ServiceContract.BAS;
using JieNor.Megi.ServiceContract.BD;
using JieNor.Megi.ServiceContract.FA;
using JieNor.Megi.ServiceContract.FC;
using JieNor.Megi.ServiceContract.FP;
using JieNor.Megi.ServiceContract.GL;
using JieNor.Megi.ServiceContract.IO;
using JieNor.Megi.ServiceContract.IV;
using JieNor.Megi.ServiceContract.MSG;
using JieNor.Megi.ServiceContract.PA;
using JieNor.Megi.ServiceContract.PT;
using JieNor.Megi.ServiceContract.REG;
using JieNor.Megi.ServiceContract.RI;
using JieNor.Megi.ServiceContract.RPT;
using JieNor.Megi.ServiceContract.SEC;
using JieNor.Megi.ServiceContract.SYS;
using System.Linq;
using System.Reflection;
using System.Web.Compilation;
using System.Web.Mvc;

namespace JieNor.Megi.Go.Web.AutoManager
{
	public class AutofacWCF
	{
		public static void BuilderWcfService()
		{
			ContainerBuilder containerBuilder = new ContainerBuilder();
			containerBuilder.RegisterControllers(BuildManager.GetReferencedAssemblies().Cast<Assembly>().ToArray());
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBASCountryRegion>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBASCurrency>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBASDataDictionary>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBASLang>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBASMyHome>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBASOrganisation>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBASTimezone>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IOptLogList>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBASCountry>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBASSearch>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBASOrgInitSetting>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBASOrgPrefixSetting>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBDAccount>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBDAttachment>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBDBankAccount>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBDBankRule>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBDBankType>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBDContacts>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBDEmployees>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBDExchangeRate>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBDExpenseItem>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBDItem>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBDTrack>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBDTrackEntry>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBDEmailTemplate>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBDAccountMatchLog>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBDVoucherSetting>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IBDInitDocument>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IGLVoucher>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IGLVoucherReference>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IGLCheckType>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IGLInitBalance>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IGLSettlement>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IGLPeriodTransfer>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IGLDocVoucher>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRIInspect>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IFCFapiaoModule>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IFCVoucherModule>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IFCCashCodingModule>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IFPTable>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IFPFapiao>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IFPSetting>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IFADepreciation>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IFAFixAssetsChange>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IFAFixAssets>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IFAFixAssetsType>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IMSGMessage>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IREGCurrency>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IREGFinancial>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IREGGlobalization>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IREGTaxRate>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTAgedInvoice>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTAgedPayable>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTAgedReceivable>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTBankAndCashSummary>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTBankBillRecSummary>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTBankStatement>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTBankStatement>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTCashSummary>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTIncomeByContact>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTIncomeTrans>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTReport>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTSalesByItemTrans>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTSalseByItem>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTSalesTaxReport>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTSalesTaxAuditReport>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTExpenseClaim>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTAccountBalance>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTGeneralLedger>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTIncomeStatement>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTBalanceSheet>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTCashFlowStatement>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTSubsidiaryLedger>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTAccountDimensionSummary>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTDepreciationDetail>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTDepreciationSummary>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTAssetChange>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRPTAssetDepreciation>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<ISECAccount>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<ISECPermission>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<ISECSendLinkInfo>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<ISECUser>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<ISECUserAccount>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IIVBankApi>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IIVBankBill>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IIVExpense>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IIVInvoice>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IIVPayment>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IIVReceive>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IIVTransactions>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IIVTransfer>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IIVVerification>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IPASalaryPayment>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IPAPayrollBasic>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<ISYSCoupon>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<ISECUserLoginLog>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IIOSolution>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IIOImport>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IRIInspect>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IPTBiz>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IPTSalaryList>()).UseWcfSafeRelease();
			containerBuilder.Register((IComponentContext c) => ServiceHostManager.GetSysService<IPTVoucher>()).UseWcfSafeRelease();
			IContainer container = containerBuilder.Build(ContainerBuildOptions.None);
			AutofacDependencyResolver resolver = new AutofacDependencyResolver(container);
			DependencyResolver.SetResolver(resolver);
		}
	}
}
