using System.Runtime.Serialization;

namespace JieNor.Megi.DataModel.IO.Export
{
	[DataContract]
	public enum ExportObjectType
	{
		[EnumMember]
		BudgetSummary = 1,
		[EnumMember]
		InventoryItemsSummary,
		[EnumMember]
		BudgetVariance,
		[EnumMember]
		ProfitAndLoss,
		[EnumMember]
		ExecutiveSummary,
		[EnumMember]
		SalesByItem,
		[EnumMember]
		ExpensesByContact,
		[EnumMember]
		SalesTaxReport,
		[EnumMember]
		IncomeByContact,
		[EnumMember]
		BankReconciliationSummary = 11,
		[EnumMember]
		CashSummary,
		[EnumMember]
		BankAndCashSummary,
		[EnumMember]
		ForeignCurrencyGainsAndLosses,
		[EnumMember]
		PayRunByEmployee,
		[EnumMember]
		PayRunByPayType,
		[EnumMember]
		PayRunByPayItem,
		[EnumMember]
		PayRunSummary,
		[EnumMember]
		AgedPayables,
		[EnumMember]
		DepreciationSchedule,
		[EnumMember]
		AgedReceivables,
		[EnumMember]
		FixedAssetReconciliation,
		[EnumMember]
		BalanceSheet,
		[EnumMember]
		MovementsInEquity,
		[EnumMember]
		AccountSummary,
		[EnumMember]
		JournalReport,
		[EnumMember]
		AccountTransactions,
		[EnumMember]
		SupplierInvoiceReport,
		[EnumMember]
		CustomerInvoiceReport,
		[EnumMember]
		TrackingSummary,
		[EnumMember]
		DetailedAccountTransactions,
		[EnumMember]
		TrialBalance,
		[EnumMember]
		GeneralLedger,
		[EnumMember]
		Invoices,
		[EnumMember]
		SalesByItemTransactions,
		[EnumMember]
		IncomeTransactions,
		[EnumMember]
		BankStatement,
		[EnumMember]
		InventoryItems = 201,
		[EnumMember]
		SaleInvoice,
		[EnumMember]
		SaleRedInvoice,
		[EnumMember]
		PurchaseInvoice,
		[EnumMember]
		PurchaseRedInvoice,
		[EnumMember]
		InvoiceList
	}
}
