namespace JieNor.Megi.Core.Log
{
	public enum OptLogTemplate
	{
		None,
		Sale_Invoice_Created,
		Sale_Invoice_Edited,
		Sale_Invoice_Deleted,
		Sale_Invoice_Approved,
		Sale_Invoice_PartiallyPaid,
		Sale_Invoice_Paid,
		Sale_Invoice_Note,
		Sale_Invoice_NoteExpectedDate,
		Sale_Invoice_Credit,
		Sale_Invoice_Credit_Delete,
		Sale_Credit_Note_Created,
		Sale_Credit_Note_Edited,
		Sale_Credit_Note_Deleted,
		Sale_Credit_Note_Approved,
		Sale_Credit_Note_Note,
		Credit_Note_Apply,
		Credit_Note_Apply_Delete,
		Sale_Credit_Note_PartiallyPaid,
		Sale_Credit_Note_Paid,
		Bill_Created = 21,
		Bill_Edited,
		Bill_Deleted,
		Bill_Approved,
		Bill_PartiallyPaid,
		Bill_Paid,
		Bill_Note,
		Bill_NoteExpectedDate,
		Bill_Credit_Note_Created = 0x1F,
		Bill_Credit_Note_Edited,
		Bill_Credit_Note_Deleted,
		Bill_Credit_Note_Approved,
		Bill_Credit_Note_Note,
		Bill_Credit_Note_PartiallyPaid,
		Bill_Credit_Note_Paid,
		Contact_Created = 41,
		Contact_Edited,
		Contact_Deleted,
		Contact_Note,
		Item_Created = 51,
		Item_Edited,
		Item_Deleted,
		Payment_Created = 61,
		Payment_Edited,
		Payment_Deleted,
		Receive_Created = 71,
		Receive_Edited,
		Receive_Deleted,
		ExpenseClaims_Created = 81,
		ExpenseClaims_Edited,
		ExpenseClaims_Deleted,
		ExpenseClaims_Approved,
		ExpenseClaims_PartiallyPaid,
		ExpenseClaims_Paid,
		ExpenseClaims_Note,
		ExpenseClaims_NoteExpectedDate,
		Sale_RepeatInvoice_UpdateStatus = 91,
		Bill_RepeatInvoice_UpdateStatus,
		Sale_RepeatInvoice_Deleted,
		Bill_RepeatInvoice_Deleted,
		Sale_Invoice_Reverse_Approved,
		Credit_Note_Reverse_Approved,
		Bill_Reverse_Approved,
		Bill_Credit_Note_Reverse_Approved,
		Sale_Invoice_Submit_For_Approval,
		Sale_Credit_Note_Submit_For_Approval,
		Bill_Submit_For_Approval,
		Bill_Credit_Note_Submit_For_Approval,
		Sale_Invoice_Edit_Account,
		Sale_Credit_Note_Edit_Account,
		Bill_Edit_Account,
		Bill_Credit_Note_Edit_Account,
		Sale_Invoice_Generate_Voucher,
		Sale_Credit_Note_Generate_Voucher,
		Bill_Generate_Voucher,
		Bill_Credit_Note_Generate_Voucher,
		ExpenseClaims_Credit,
		ExpenseClaims_Credit_Delete,
		ExpenseClaims_Reverse_Approved,
		ExpenseClaims_Submit_For_Approval,
		ExpenseClaims_Edit_Account,
		ExpenseClaims_Generate_Voucher,
		Sale_GoldenTaxInvoice_Created = 1001,
		Sale_GoldenTaxInvoice_Edited,
		Sale_GoldenTaxInvoice_Deleted,
		Sale_GoldenTaxInvoice_UpdateExpressInfo = 1003,
		Sale_GoldenTaxInvoice_UpdatePrintStatus = 1005,
		Sale_GoldenTaxInvoice_Note,
		Bill_GoldenTaxInvoice_Created,
		Bill_GoldenTaxInvoice_Edited,
		Bill_GoldenTaxInvoice_Deleted,
		Bill_GoldenTaxInvoice_UpdateExpressInfo,
		Bill_GoldenTaxInvoice_UpdatePrintStatus,
		Bill_GoldenTaxInvoice_Note,
		SalaryPayment_Created = 1020,
		SalaryPayment_Edited,
		SalaryPayment_Deleted,
		SalaryPayment_Approved,
		SalaryPayment_PartiallyPaid,
		SalaryPayment_Paid,
		SalaryPayment_Note,
		SalaryPayment_NoteExpectedDate,
		SalaryPayment_Reverse_Approved,
		Sale_FaPiao_Created = 2001,
		Sale_FaPiao_Edited,
		Sale_FaPiao_Deleted,
		FaPiao_Note = 2015,
		FaPiao_ManualReconcie = 2018,
		Fapiao_RemoveReconcile,
		Fapiao_BatchUpdateFPStatus,
		Fapiao_BatchUpdateFPVerifyType,
		Sale_FaPiao_Table_Created = 2004,
		Sale_FaPiao_Table_Edited,
		Sale_FaPiao_Table_Deleted,
		Sale_FaPiao_Note = 2016,
		GL_Voucher_Created = 2007,
		GL_Voucher_Edited,
		GL_Voucher_Deleted,
		GL_Voucher_Approval,
		GL_Voucher_ReverseApprove,
		GL_Voucher_CreateReverse = 2013,
		GL_Voucher_ApplyReverse,
		GL_Voucher_Note = 2017,
		Attachment_Upload = 3001,
		Attachment_Remove,
		Attachment_Delete,
		Sale_FaPiao_Import_Deleted
	}
}
