using System.Runtime.Serialization;

namespace JieNor.Megi.Core
{
	[DataContract]
	public enum BizReportType
	{
		[EnumMember]
		None,
		[EnumMember]
		BudgetSummary,
		[EnumMember]
		InventoryItemsSummary,
		[EnumMember]
		BudgetVariance,
		[EnumMember]
		ProfitAndLoss,
		[EnumMember]
		ExecutiveSummary,
		[EnumMember]
		SalesByItem,
		[EnumMember]
		ExpensesByContact,
		[EnumMember]
		SalesTaxReport,
		[EnumMember]
		IncomeByContact,
		[EnumMember]
		BankReconciliationSummary = 11,
		[EnumMember]
		CashSummary,
		[EnumMember]
		BankAndCashSummary,
		[EnumMember]
		ForeignCurrencyGainsAndLosses,
		[EnumMember]
		PayRunByEmployee,
		[EnumMember]
		PayRunByPayType,
		[EnumMember]
		PayRunByPayItem,
		[EnumMember]
		PayRunSummary,
		[EnumMember]
		AgedPayables,
		[EnumMember]
		DepreciationSchedule,
		[EnumMember]
		AgedReceivables,
		[EnumMember]
		FixedAssetReconciliation,
		[EnumMember]
		BalanceSheet,
		[EnumMember]
		MovementsInEquity,
		[EnumMember]
		AccountSummary,
		[EnumMember]
		JournalReport,
		[EnumMember]
		AccountTransactions,
		[EnumMember]
		SupplierInvoiceReport,
		[EnumMember]
		CustomerInvoiceReport,
		[EnumMember]
		TrackingSummary,
		[EnumMember]
		DetailedAccountTransactions,
		[EnumMember]
		TrialBalance,
		[EnumMember]
		GeneralLedger,
		[EnumMember]
		Invoices,
		[EnumMember]
		SalesByItemTransactions,
		[EnumMember]
		IncomeTransactions,
		[EnumMember]
		BankStatement,
		[EnumMember]
		ExpenseClaims,
		[EnumMember]
		IncomeStatement,
		[EnumMember]
		CashFlowStatement,
		[EnumMember]
		AccountBalance,
		[EnumMember]
		SubsidiaryLedger,
		[EnumMember]
		AccountDimensionSummary,
		[EnumMember]
		InventoryItems = 201,
		[EnumMember]
		SaleInvoice,
		[EnumMember]
		SaleRedInvoice,
		[EnumMember]
		PurchaseInvoice,
		[EnumMember]
		PurchaseRedInvoice,
		[EnumMember]
		InvoiceList,
		[EnumMember]
		ContactList,
		[EnumMember]
		Statements,
		[EnumMember]
		InvoiceListPrint,
		[EnumMember]
		BillListPrint,
		[EnumMember]
		PurchaseList,
		[EnumMember]
		EmployeeList,
		[EnumMember]
		ExpenseList,
		[EnumMember]
		TransactionList,
		[EnumMember]
		Accounts,
		[EnumMember]
		VoucherList,
		[EnumMember]
		VoucherPrint,
		[EnumMember]
		OpeningBalances,
		[EnumMember]
		ExpenseClaimsPrint,
		[EnumMember]
		SalaryPrint,
		[EnumMember]
		ExpenseItem = 230,
		[EnumMember]
		ExpenseClaimDetail = 381,
		[EnumMember]
		DepreciationDetail = 501,
		[EnumMember]
		DepreciationSummary,
		[EnumMember]
		AssetChange,
		[EnumMember]
		AssetDepreciation,
		[EnumMember]
		AssetCardList,
		[EnumMember]
		InputInvoice = 600,
		[EnumMember]
		OutputInvoice = 700
	}
}
