using System.Runtime.Serialization;

namespace JieNor.Megi.EntityModel.Enum
{
	[DataContract]
	public enum MActionResultCodeEnum
	{
		[EnumMember]
		Success = 200,
		[EnumMember]
		AccessTokenMissing = 400,
		[EnumMember]
		ContextMissing,
		[EnumMember]
		ContextExpired,
		[EnumMember]
		UnTracableAddress,
		[EnumMember]
		AddressNotMatch,
		[EnumMember]
		OrgExpired,
		[EnumMember]
		SyncBusy,
		[EnumMember]
		AccessDenied = 501,
		[EnumMember]
		ExceptionExist,
		[EnumMember]
		MContactInvalid = 900,
		[EnumMember]
		MEmployeeInvalid,
		[EnumMember]
		MMerItemInvalid,
		[EnumMember]
		MExpItemInvalid,
		[EnumMember]
		MPaItemInvalid,
		[EnumMember]
		MTrackItemInvalid,
		[EnumMember]
		MNumberInvalid,
		[EnumMember]
		MAccountInvalid,
		[EnumMember]
		MCurrencyInvalid,
		[EnumMember]
		MPeriodClosed,
		[EnumMember]
		MPeriodBeforeStart,
		[EnumMember]
		MVoucherApproved,
		[EnumMember]
		MVoucherUnapprove,
		[EnumMember]
		MPeriodTransferExists,
		[EnumMember]
		MInitBalanceOver,
		[EnumMember]
		MTrackGroupInvalid,
		[EnumMember]
		MAccountHasSub,
		[EnumMember]
		MExpItemHasSub,
		[EnumMember]
		MCheckGroupValueNotMatchWithAccount,
		[EnumMember]
		MVoucherHasNotEntry,
		[EnumMember]
		MCreditDebitImbalance,
		[EnumMember]
		MVoucherEntryHasNotAccountOrAccountNotMatchCheckGroup,
		[EnumMember]
		MVoucherModuleFastCodeInvalid,
		[EnumMember]
		MCurrencyNotMatchAccount,
		[EnumMember]
		MOneDocCreatedMoreThanOneVoucher,
		[EnumMember]
		MHasUnsettledPeriodBefore,
		[EnumMember]
		MInvalidDocExsits,
		[EnumMember]
		MAccountNumberDuplicated,
		[EnumMember]
		MAccountNameDuplicated,
		[EnumMember]
		MAccountParentInvalid,
		[EnumMember]
		MAccountNewCheckGroupNotMathWithOldData,
		[EnumMember]
		MAccountDetailIncomplete,
		[EnumMember]
		MVoucherExplanationDuplicated,
		[EnumMember]
		MVoucherExplanationInvalid,
		[EnumMember]
		MVoucherInvalid,
		[EnumMember]
		MBillHasAlreadyCreatedVoucher,
		[EnumMember]
		MBankAccountInvalid,
		[EnumMember]
		MFixAssetsTypeNumberDuplicated,
		[EnumMember]
		MFixAssetsTypeNameDuplicated,
		[EnumMember]
		MFixAssetsNumberDuplicated,
		[EnumMember]
		MFixAssetsNameDuplicated,
		[EnumMember]
		MFixAssetsTypeRelatedFixAssets,
		[EnumMember]
		MFixAssetsAlreadyDepreciated,
		[EnumMember]
		MFixAssetsAlreadyDisposed,
		[EnumMember]
		MFixAssetsIsNormal,
		[EnumMember]
		MDeprecationVoucherCreated,
		[EnumMember]
		MFixAssetsInvalid,
		[EnumMember]
		MAccountAreRequiredForDepreciation,
		[EnumMember]
		MDepreciatedVoucherHasBeenCreatedDuringItsHandledPeriod,
		[EnumMember]
		MExistsCreatedDepreciationVoucherAfterThisPeriod,
		[EnumMember]
		MExistsUnDepreciatedPeriodBefore,
		[EnumMember]
		MDepreciationVoucherIsApproved,
		[EnumMember]
		MExistsChangeAfterThisPeriod,
		[EnumMember]
		MResubmitException,
		[EnumMember]
		MLoginInfoLost,
		[EnumMember]
		MFapiaoDeletedOrObsolete,
		[EnumMember]
		MTableNotExists,
		[EnumMember]
		MFapiaoAmountCannotLargerThanTableAmount,
		[EnumMember]
		MExistsFapiaoInReconciledStatus,
		[EnumMember]
		MExistsFapiaoInNoReconciledStatus,
		[EnumMember]
		MExistsFapiaoInNoCodingStatus,
		[EnumMember]
		MExistsFapiaoCreatedFapiao,
		[EnumMember]
		MFapiaoCreateVoucherWithNoContact,
		[EnumMember]
		MFapiaoCreateVoucherWithNoDebitAccount,
		[EnumMember]
		MFapiaoCreateVoucherWithNoCreditAccount,
		[EnumMember]
		MFapiaoCreateVoucherWithNoTaxAccount,
		[EnumMember]
		MFapiaoModuleFastCodeInvalid,
		[EnumMember]
		MOutFapiaoPeriodIsClosed,
		[EnumMember]
		MOutFapiaoPeriodStartGL,
		[EnumMember]
		MExistsReconciledFapiao = 980,
		[EnumMember]
		MExistsVoucherNumberLagerThanSetLength,
		[EnumMember]
		MVoucherNumberNotMeetDemand,
		[EnumMember]
		MVoucherEntryMoreThanOne,
		[EnumMember]
		MVoucherDeleted,
		[EnumMember]
		MVoucherSpanApprove,
		MExistsFapiaoCreatedVoucher = 1000,
		[EnumMember]
		MValid = 999
	}
}
